/* Generated By:JJTree: Do not edit this line. ASTDocument.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

public class ASTDocument extends ComplexNode {

	@Override
	public String getCode() {
		return "\\begin{document}" + 
			super.getCode() +
			"\\end{document}";
	}

	public ASTDocument(int id) {
		super(id);
	}

	public ASTDocument(TexParser p, int id) {
		super(p, id);
	}

}
