/* Generated By:JJTree: Do not edit this line. ASTMultiChoice.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

public class ASTMultiChoice extends ComplexNode {
	
	@Override
	public String getCode() {
		return "%%CHOICE\n" + super.getCode();
	}

	public ASTMultiChoice(int id) {
		super(id);
	}

	public ASTMultiChoice(TexParser p, int id) {
		super(p, id);
	}

}
