/* Generated By:JJTree: Do not edit this line. ASTRepeat.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

import java.util.Set;

import au.edu.uq.smartassrepoeditor.script.Script;

public class ASTRepeat extends ComplexNode {
	int repeats_num;
	
	public int getRepeatsNum() {
		return repeats_num;
	}
	
	public void setRepeatsNum(int repeats_num) {
		this.repeats_num = repeats_num;
	}
	
	@Override
	public String getCode() {
		return "%%REPEAT " + Integer.toString(repeats_num) + "\n" +
			super.getCode()
			+ "%%ENDREPEAT\n";
	}
	
	@Override
	public RComplexNode execute(Set<String> sections, Script script) {
		ASTRepeatItem n = new ASTRepeatItem();
		n.children = children;
		RComplexNode result = new RComplexNode(this);
		for(int i=0;i<repeats_num;i++) 
			result.addChild(n.execute(sections, script));
		is_executed = true;
		return result;
	}
	
	public ASTRepeat(int id) {
		super(id);
	}

	public ASTRepeat(TexParser p, int id) {
		super(p, id);
	}

}
