/* Generated By:JJTree: Do not edit this line. ASTSection.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

import java.util.Set;

import au.edu.uq.smartassrepoeditor.script.Script;



public class ASTSection extends ComplexNode {
	private String name;

	public ASTSection(int id) {
		super(id);
	}

	public ASTSection(TexParser p, int id) {
		super(p, id);
	}

	/**
	 * Getter method for name
	 * 
	 * @return 	section name
	 */
	public String getName() {
		return name;
	}
	
	/**
	 * Setter method for name
	 * 
	 * @param name		section name
	 */
	public void setName(String name) {
		this.name = name;
	}
	
	@Override
	public String getCode() {
		return "%%BEGIN " + getName() + "\n" + 
			super.getCode() +
			"%%END " + getName() + "\n";
	}
	
	@Override
	public RComplexNode execute(Set<String> sections, Script script) {
		is_executed = true;
		sections.add(name);
		return executeChildren(new RSection(this), sections, script);
	}

}
