/* Generated By:JJTree: Do not edit this line. ASTTemplate.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

import java.util.Set;
import java.util.Vector;

import au.edu.uq.smartassrepoeditor.script.Script;

public class ASTTemplate extends ComplexNode {
	protected ASTAnyText header;
	protected ASTDocument doc;
	
	public void init() {
		header = (ASTAnyText) children[0];
		if(header==null) {
			header = new ASTAnyText(0);
			header.setText("");
		}
		doc = (ASTDocument) children[1];
	}
	
	@Override
	public RTemplate execute(Set<String> sections, Script script) {
		is_executed = true;
		return new RTemplate(this, header.execute(sections, script), doc.execute(sections, script));
	}
	
	@Override
	public String getCode() {
		return super.getCode();
	}
	
	public ASTDocument getDocument() {
		return doc;
	}
	
	public ASTTemplate(int id) {
		super(id);
	}

	public ASTTemplate(TexParser p, int id) {
		super(p, id);
	}

}
