/* Generated By:JJTree: Do not edit this line. ./TexParserTreeConstants.java */

package au.edu.uq.smartassrepoeditor.templates.texparser;

public interface TexParserTreeConstants
{
  public int JJTTEMPLATE = 0;
  public int JJTDOCUMENT = 1;
  public int JJTVOID = 2;
  public int JJTREPEAT = 3;
  public int JJTMULTI = 4;
  public int JJTMULTICHOICE = 5;
  public int JJTCALL = 6;
  public int JJTSECTION = 7;
  public int JJTSCRIPT = 8;
  public int JJTANYTEXT = 9;


  public String[] jjtNodeName = {
    "Template",
    "Document",
    "void",
    "Repeat",
    "Multi",
    "MultiChoice",
    "Call",
    "Section",
    "Script",
    "AnyText",
  };
}
