/* Generated By:JavaCC: Do not edit this line. SimpleScriptParserConstants.java */
package au.edu.uq.smartassrepoeditor.script.ssparser;

public interface SimpleScriptParserConstants {

  int EOF = 0;
  int SPACE = 4;
  int LINEDELIMITER = 5;
  int ALPHA = 6;
  int FILEDELIMITER = 7;
  int NUMBER = 8;
  int SEQUENTIAL = 9;
  int RANDOM = 10;
  int UNIQUE = 11;
  int KEY = 12;
  int SPACES = 13;
  int NAME = 14;
  int NUMBERS = 15;
  int DSRANGLE = 16;
  int DSLANGLE = 17;
  int OPENDSBRACKET = 18;
  int DEFQUOTE = 19;
  int DEFENDQUOTE = 20;
  int DEFNOQUOTES = 21;
  int OPENBRACKET = 22;
  int CLOSEBRACKET = 23;
  int PARAMDSLANGLE = 24;
  int DSSHARP = 25;
  int PARAMDSRANGLE = 26;
  int QUOTE = 27;
  int ENDQUOTE = 28;
  int NOQUOTES = 29;
  int COMMA = 30;
  int NOSTRING = 31;
  int NOCOMMA = 32;

  int DEFAULT = 0;
  int DSCREATION = 1;
  int PARAM = 2;
  int DSNAME = 3;
  int DEFSTRING = 4;
  int STRING = 5;

  String[] tokenImage = {
    "<EOF>",
    "\".\"",
    "\",\"",
    "\")\"",
    "<SPACE>",
    "\";\"",
    "<ALPHA>",
    "\"/\"",
    "<NUMBER>",
    "\"SEQUENTIAL\"",
    "\"RANDOM\"",
    "\"UNIQUE\"",
    "\"KEY\"",
    "<SPACES>",
    "<NAME>",
    "<NUMBERS>",
    "\">\"",
    "\"<\"",
    "\"(\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<DEFNOQUOTES>",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\"#\"",
    "\">\"",
    "\"\\\"\"",
    "\"\\\"\"",
    "<NOQUOTES>",
    "\",\"",
    "<NOSTRING>",
    "<NOCOMMA>",
  };

}
